#########################################################################
# DESCRIPTION: Code to create VE curves for Overall Dengue ENdpoint by AUC-MB cases using Mon 13 titer
#              Logistic regression, No hinge model.
#              CI is acquired using bootstrap.
#              W's are dichotomize Age at 11 and Country (did not include Gender) 
#              Assume no effect of covariate (W) in risk model 
#              Y=ofstatus_m13
#              S=AUC-MB
#
# CODED BY: Yingying Zhuang
# SAVED AS: CYD15VE_hinge.R
#
# HISTORY:
# Date      Programmer   	
# Dec19-2015  Y Zhuang      Version 1
##########################################################################
library("kyotil",lib.loc="~/R/library")
library(MASS)
library("chngpt",lib.loc="~/R/library")
rm(list=ls(all=TRUE))

short<-"noW"

dirName <- "."

#read in data
m13CoRdata <- read.csv(file.path(dirName, "cyd15m13CoRdata_hosp_ap.csv"), header=TRUE)
# m13CoRdata is the Mon13 CoR Analysis Population: Month 13 cases and controls at risk at Mon 13 and uninfected prior to Mon13:

dat <- m13CoRdata[,c("SUBJID","AGEYRS","SEX","COUNTRY")]
dat$Y <- m13CoRdata$ofstatus_m13
dat$Z <- m13CoRdata$VACC
dat$S <- m13CoRdata$IMPSTLOG.AUCMB                                                      
dat$S1 <- ifelse(dat$Z==1,dat$S,NA) #S(1):vaccine-induced immune response

dat$AGE<-cut(dat$AGEYRS,c(0,11,17))

### Only include Age and Country as W's
dat$W <- as.numeric(factor(dat$AGE))*100+as.numeric(factor(dat$COUNTRY))
dat$delta.CPV <- !is.na(dat$S1)
#Done with creat working dataset "dat"


#need to pass dat and short to slaves

#####Starting parallel computing
library("Rmpi")
mpi.spawn.Rslaves(nslaves=125)
#Send "dat" to slaves 
mpi.bcast.Robj2slave(dat)
#Send "thre" to slaves the temper function
mpi.bcast.Robj2slave(short) 

source(file.path(dirName,"CYD15VE_Nohinge_bCI_slaveLoad.R"))
mpi.bcast.cmd(source("./CYD15VE_Nohinge_bCI_slaveLoad.R"))

system.time(results <- mpi.remote.exec(bVE.Nohinge(iter=8),ret=TRUE))
save(results,file=paste0("CYD15VE_Nohinge_","bCI_",short,"_",format(Sys.Date(),"%m%d%Y"),".RData"))

#shut down the slaves.  Delete the log file generated by each slave,
mpi.close.Rslaves(dellog=TRUE)
mpi.quit(save = "no")
